import { useState, useMemo, useCallback } from "react"

const EMOJI_DATA: { emoji: string; name: string; category: string }[] = [
  { emoji: "😀", name: "grinning face", category: "smileys" },
  { emoji: "😃", name: "grinning face with big eyes", category: "smileys" },
  { emoji: "😄", name: "grinning face with smiling eyes", category: "smileys" },
  { emoji: "😁", name: "beaming face with smiling eyes", category: "smileys" },
  { emoji: "😆", name: "grinning squinting face", category: "smileys" },
  { emoji: "😅", name: "grinning face with sweat", category: "smileys" },
  { emoji: "🤣", name: "rolling on the floor laughing", category: "smileys" },
  { emoji: "😂", name: "face with tears of joy", category: "smileys" },
  { emoji: "🙂", name: "slightly smiling face", category: "smileys" },
  { emoji: "🙃", name: "upside-down face", category: "smileys" },
  { emoji: "😉", name: "winking face", category: "smileys" },
  { emoji: "😊", name: "smiling face with smiling eyes", category: "smileys" },
  { emoji: "😇", name: "smiling face with halo", category: "smileys" },
  { emoji: "🥰", name: "smiling face with hearts", category: "smileys" },
  { emoji: "😍", name: "heart eyes", category: "smileys" },
  { emoji: "🤩", name: "star struck", category: "smileys" },
  { emoji: "😘", name: "face blowing a kiss", category: "smileys" },
  { emoji: "😗", name: "kissing face", category: "smileys" },
  { emoji: "😚", name: "kissing closed eyes", category: "smileys" },
  { emoji: "😙", name: "kissing smiling eyes", category: "smileys" },
  { emoji: "🥲", name: "smiling face with tear", category: "smileys" },
  { emoji: "😋", name: "face savoring food", category: "smileys" },
  { emoji: "😛", name: "face with tongue", category: "smileys" },
  { emoji: "😜", name: "winking face with tongue", category: "smileys" },
  { emoji: "🤪", name: "zany face", category: "smileys" },
  { emoji: "😝", name: "squinting face with tongue", category: "smileys" },
  { emoji: "🤑", name: "money mouth face", category: "smileys" },
  { emoji: "🤗", name: "hugging face", category: "smileys" },
  { emoji: "🤭", name: "face with hand over mouth", category: "smileys" },
  { emoji: "🫢", name: "face with open eyes and hand over mouth", category: "smileys" },
  { emoji: "🤫", name: "shushing face", category: "smileys" },
  { emoji: "🤔", name: "thinking face", category: "smileys" },
  { emoji: "🫡", name: "saluting face", category: "smileys" },
  { emoji: "🤐", name: "zipper mouth face", category: "smileys" },
  { emoji: "🤨", name: "face with raised eyebrow", category: "smileys" },
  { emoji: "😐", name: "neutral face", category: "smileys" },
  { emoji: "😑", name: "expressionless face", category: "smileys" },
  { emoji: "😶", name: "face without mouth", category: "smileys" },
  { emoji: "😏", name: "smirking face", category: "smileys" },
  { emoji: "😒", name: "unamused face", category: "smileys" },
  { emoji: "🙄", name: "face with rolling eyes", category: "smileys" },
  { emoji: "😬", name: "grimacing face", category: "smileys" },
  { emoji: "😮‍💨", name: "face exhaling", category: "smileys" },
  { emoji: "🤥", name: "lying face", category: "smileys" },
  { emoji: "😌", name: "relieved face", category: "smileys" },
  { emoji: "😔", name: "pensive face", category: "smileys" },
  { emoji: "😪", name: "sleepy face", category: "smileys" },
  { emoji: "🤤", name: "drooling face", category: "smileys" },
  { emoji: "😴", name: "sleeping face", category: "smileys" },
  { emoji: "😷", name: "face with medical mask", category: "smileys" },
  { emoji: "🤒", name: "face with thermometer", category: "smileys" },
  { emoji: "🤕", name: "face with head bandage", category: "smileys" },
  { emoji: "🤢", name: "nauseated face", category: "smileys" },
  { emoji: "🤮", name: "face vomiting", category: "smileys" },
  { emoji: "🤧", name: "sneezing face", category: "smileys" },
  { emoji: "🥵", name: "hot face", category: "smileys" },
  { emoji: "🥶", name: "cold face", category: "smileys" },
  { emoji: "🥴", name: "woozy face", category: "smileys" },
  { emoji: "😵", name: "face with crossed out eyes", category: "smileys" },
  { emoji: "🤯", name: "exploding head", category: "smileys" },
  { emoji: "🤠", name: "cowboy hat face", category: "smileys" },
  { emoji: "🥳", name: "partying face", category: "smileys" },
  { emoji: "🥸", name: "disguised face", category: "smileys" },
  { emoji: "😎", name: "smiling face with sunglasses", category: "smileys" },
  { emoji: "🤓", name: "nerd face", category: "smileys" },
  { emoji: "🧐", name: "face with monocle", category: "smileys" },
  { emoji: "😕", name: "confused face", category: "smileys" },
  { emoji: "🫤", name: "face with diagonal mouth", category: "smileys" },
  { emoji: "😟", name: "worried face", category: "smileys" },
  { emoji: "🙁", name: "slightly frowning face", category: "smileys" },
  { emoji: "😮", name: "face with open mouth", category: "smileys" },
  { emoji: "😯", name: "hushed face", category: "smileys" },
  { emoji: "😲", name: "astonished face", category: "smileys" },
  { emoji: "😳", name: "flushed face", category: "smileys" },
  { emoji: "🥺", name: "pleading face", category: "smileys" },
  { emoji: "🥹", name: "face holding back tears", category: "smileys" },
  { emoji: "😦", name: "frowning face with open mouth", category: "smileys" },
  { emoji: "😧", name: "anguished face", category: "smileys" },
  { emoji: "😨", name: "fearful face", category: "smileys" },
  { emoji: "😰", name: "anxious face with sweat", category: "smileys" },
  { emoji: "😥", name: "sad but relieved face", category: "smileys" },
  { emoji: "😢", name: "crying face", category: "smileys" },
  { emoji: "😭", name: "loudly crying face", category: "smileys" },
  { emoji: "😱", name: "face screaming in fear", category: "smileys" },
  { emoji: "😖", name: "confounded face", category: "smileys" },
  { emoji: "😣", name: "persevering face", category: "smileys" },
  { emoji: "😞", name: "disappointed face", category: "smileys" },
  { emoji: "😓", name: "downcast face with sweat", category: "smileys" },
  { emoji: "😩", name: "weary face", category: "smileys" },
  { emoji: "😫", name: "tired face", category: "smileys" },
  { emoji: "🥱", name: "yawning face", category: "smileys" },
  { emoji: "😤", name: "face with steam from nose", category: "smileys" },
  { emoji: "😡", name: "pouting face", category: "smileys" },
  { emoji: "😠", name: "angry face", category: "smileys" },
  { emoji: "🤬", name: "face with symbols on mouth", category: "smileys" },
  { emoji: "😈", name: "smiling face with horns", category: "smileys" },
  { emoji: "👿", name: "angry face with horns", category: "smileys" },
  { emoji: "💀", name: "skull", category: "smileys" },
  { emoji: "💩", name: "pile of poo", category: "smileys" },
  { emoji: "🤡", name: "clown face", category: "smileys" },
  { emoji: "👹", name: "ogre", category: "smileys" },
  { emoji: "👺", name: "goblin", category: "smileys" },
  { emoji: "👻", name: "ghost", category: "smileys" },
  { emoji: "👽", name: "alien", category: "smileys" },
  { emoji: "👾", name: "alien monster", category: "smileys" },
  { emoji: "🤖", name: "robot", category: "smileys" },
  { emoji: "👋", name: "waving hand", category: "people" },
  { emoji: "🤚", name: "raised back of hand", category: "people" },
  { emoji: "🖐️", name: "hand with fingers splayed", category: "people" },
  { emoji: "✋", name: "raised hand", category: "people" },
  { emoji: "🖖", name: "vulcan salute", category: "people" },
  { emoji: "👌", name: "OK hand", category: "people" },
  { emoji: "🤌", name: "pinched fingers", category: "people" },
  { emoji: "🤏", name: "pinching hand", category: "people" },
  { emoji: "✌️", name: "victory hand", category: "people" },
  { emoji: "🤞", name: "crossed fingers", category: "people" },
  { emoji: "🤟", name: "love you gesture", category: "people" },
  { emoji: "🤘", name: "sign of the horns", category: "people" },
  { emoji: "🤙", name: "call me hand", category: "people" },
  { emoji: "👈", name: "backhand index pointing left", category: "people" },
  { emoji: "👉", name: "backhand index pointing right", category: "people" },
  { emoji: "👆", name: "backhand index pointing up", category: "people" },
  { emoji: "🖕", name: "middle finger", category: "people" },
  { emoji: "👇", name: "backhand index pointing down", category: "people" },
  { emoji: "👍", name: "thumbs up", category: "people" },
  { emoji: "👎", name: "thumbs down", category: "people" },
  { emoji: "✊", name: "raised fist", category: "people" },
  { emoji: "👊", name: "oncoming fist", category: "people" },
  { emoji: "🤛", name: "left-facing fist", category: "people" },
  { emoji: "🤜", name: "right-facing fist", category: "people" },
  { emoji: "👏", name: "clapping hands", category: "people" },
  { emoji: "🙌", name: "raising hands", category: "people" },
  { emoji: "👐", name: "open hands", category: "people" },
  { emoji: "🤲", name: "palms up together", category: "people" },
  { emoji: "🤝", name: "handshake", category: "people" },
  { emoji: "🙏", name: "folded hands", category: "people" },
  { emoji: "🐱", name: "cat face", category: "animals" },
  { emoji: "🐶", name: "dog face", category: "animals" },
  { emoji: "🐭", name: "mouse face", category: "animals" },
  { emoji: "🐹", name: "hamster", category: "animals" },
  { emoji: "🐰", name: "rabbit face", category: "animals" },
  { emoji: "🦊", name: "fox", category: "animals" },
  { emoji: "🐻", name: "bear", category: "animals" },
  { emoji: "🐼", name: "panda", category: "animals" },
  { emoji: "🐨", name: "koala", category: "animals" },
  { emoji: "🐯", name: "tiger face", category: "animals" },
  { emoji: "🦁", name: "lion", category: "animals" },
  { emoji: "🐮", name: "cow face", category: "animals" },
  { emoji: "🐷", name: "pig face", category: "animals" },
  { emoji: "🐸", name: "frog", category: "animals" },
  { emoji: "🐵", name: "monkey face", category: "animals" },
  { emoji: "🐔", name: "chicken", category: "animals" },
  { emoji: "🐧", name: "penguin", category: "animals" },
  { emoji: "🐦", name: "bird", category: "animals" },
  { emoji: "🐤", name: "baby chick", category: "animals" },
  { emoji: "🦅", name: "eagle", category: "animals" },
  { emoji: "🦆", name: "duck", category: "animals" },
  { emoji: "🦉", name: "owl", category: "animals" },
  { emoji: "🦇", name: "bat", category: "animals" },
  { emoji: "🐺", name: "wolf", category: "animals" },
  { emoji: "🐗", name: "boar", category: "animals" },
  { emoji: "🐴", name: "horse face", category: "animals" },
  { emoji: "🦄", name: "unicorn", category: "animals" },
  { emoji: "🐝", name: "honeybee", category: "animals" },
  { emoji: "🐛", name: "bug", category: "animals" },
  { emoji: "🦋", name: "butterfly", category: "animals" },
  { emoji: "🐌", name: "snail", category: "animals" },
  { emoji: "🐜", name: "ant", category: "animals" },
  { emoji: "🪲", name: "beetle", category: "animals" },
  { emoji: "🐢", name: "turtle", category: "animals" },
  { emoji: "🐍", name: "snake", category: "animals" },
  { emoji: "🦎", name: "lizard", category: "animals" },
  { emoji: "🐙", name: "octopus", category: "animals" },
  { emoji: "🦑", name: "squid", category: "animals" },
  { emoji: "🐠", name: "tropical fish", category: "animals" },
  { emoji: "🐟", name: "fish", category: "animals" },
  { emoji: "🐡", name: "blowfish", category: "animals" },
  { emoji: "🐬", name: "dolphin", category: "animals" },
  { emoji: "🐳", name: "spouting whale", category: "animals" },
  { emoji: "🐋", name: "whale", category: "animals" },
  { emoji: "🦈", name: "shark", category: "animals" },
  { emoji: "🐊", name: "crocodile", category: "animals" },
  { emoji: "🐅", name: "tiger", category: "animals" },
  { emoji: "🐆", name: "leopard", category: "animals" },
  { emoji: "🦓", name: "zebra", category: "animals" },
  { emoji: "🦏", name: "rhinoceros", category: "animals" },
  { emoji: "🐘", name: "elephant", category: "animals" },
  { emoji: "🦛", name: "hippopotamus", category: "animals" },
  { emoji: "🐪", name: "camel", category: "animals" },
  { emoji: "🐫", name: "two-hump camel", category: "animals" },
  { emoji: "🦒", name: "giraffe", category: "animals" },
  { emoji: "🦘", name: "kangaroo", category: "animals" },
  { emoji: "🍎", name: "red apple", category: "food" },
  { emoji: "🍐", name: "pear", category: "food" },
  { emoji: "🍊", name: "tangerine", category: "food" },
  { emoji: "🍋", name: "lemon", category: "food" },
  { emoji: "🍌", name: "banana", category: "food" },
  { emoji: "🍉", name: "watermelon", category: "food" },
  { emoji: "🍇", name: "grapes", category: "food" },
  { emoji: "🍓", name: "strawberry", category: "food" },
  { emoji: "🫐", name: "blueberries", category: "food" },
  { emoji: "🍈", name: "melon", category: "food" },
  { emoji: "🍒", name: "cherries", category: "food" },
  { emoji: "🍑", name: "peach", category: "food" },
  { emoji: "🥭", name: "mango", category: "food" },
  { emoji: "🍍", name: "pineapple", category: "food" },
  { emoji: "🥥", name: "coconut", category: "food" },
  { emoji: "🥝", name: "kiwi fruit", category: "food" },
  { emoji: "🍅", name: "tomato", category: "food" },
  { emoji: "🥑", name: "avocado", category: "food" },
  { emoji: "🥦", name: "broccoli", category: "food" },
  { emoji: "🥕", name: "carrot", category: "food" },
  { emoji: "🌽", name: "ear of corn", category: "food" },
  { emoji: "🌶️", name: "hot pepper", category: "food" },
  { emoji: "🫑", name: "bell pepper", category: "food" },
  { emoji: "🥒", name: "cucumber", category: "food" },
  { emoji: "🥬", name: "leafy green", category: "food" },
  { emoji: "🥔", name: "potato", category: "food" },
  { emoji: "🍞", name: "bread", category: "food" },
  { emoji: "🥐", name: "croissant", category: "food" },
  { emoji: "🥖", name: "baguette bread", category: "food" },
  { emoji: "🧀", name: "cheese wedge", category: "food" },
  { emoji: "🍖", name: "meat on bone", category: "food" },
  { emoji: "🍗", name: "poultry leg", category: "food" },
  { emoji: "🥩", name: "cut of meat", category: "food" },
  { emoji: "🍔", name: "hamburger", category: "food" },
  { emoji: "🍟", name: "french fries", category: "food" },
  { emoji: "🍕", name: "pizza", category: "food" },
  { emoji: "🌭", name: "hot dog", category: "food" },
  { emoji: "🥪", name: "sandwich", category: "food" },
  { emoji: "🌮", name: "taco", category: "food" },
  { emoji: "🌯", name: "burrito", category: "food" },
  { emoji: "🥚", name: "egg", category: "food" },
  { emoji: "🍳", name: "cooking", category: "food" },
  { emoji: "🧈", name: "butter", category: "food" },
  { emoji: "🥞", name: "pancakes", category: "food" },
  { emoji: "🧇", name: "waffle", category: "food" },
  { emoji: "🥓", name: "bacon", category: "food" },
  { emoji: "🥩", name: "steak", category: "food" },
  { emoji: "🍝", name: "spaghetti", category: "food" },
  { emoji: "🍜", name: "steaming bowl", category: "food" },
  { emoji: "🍲", name: "pot of food", category: "food" },
  { emoji: "🍛", name: "curry rice", category: "food" },
  { emoji: "🍣", name: "sushi", category: "food" },
  { emoji: "🍱", name: "bento box", category: "food" },
  { emoji: "🥟", name: "dumpling", category: "food" },
  { emoji: "🍦", name: "soft ice cream", category: "food" },
  { emoji: "🍧", name: "shaved ice", category: "food" },
  { emoji: "🍨", name: "ice cream", category: "food" },
  { emoji: "🍩", name: "doughnut", category: "food" },
  { emoji: "🍪", name: "cookie", category: "food" },
  { emoji: "🎂", name: "birthday cake", category: "food" },
  { emoji: "🍰", name: "shortcake", category: "food" },
  { emoji: "☕", name: "hot beverage", category: "food" },
  { emoji: "🍵", name: "teacup without handle", category: "food" },
  { emoji: "🧃", name: "beverage box", category: "food" },
  { emoji: "🥤", name: "cup with straw", category: "food" },
  { emoji: "🍺", name: "beer mug", category: "food" },
  { emoji: "🍻", name: "clinking beer mugs", category: "food" },
  { emoji: "🥂", name: "clinking glasses", category: "food" },
  { emoji: "🍷", name: "wine glass", category: "food" },
  { emoji: "🚗", name: "automobile", category: "travel" },
  { emoji: "🚕", name: "taxi", category: "travel" },
  { emoji: "🚙", name: "sport utility vehicle", category: "travel" },
  { emoji: "🚌", name: "bus", category: "travel" },
  { emoji: "🚎", name: "trolleybus", category: "travel" },
  { emoji: "🏎️", name: "racing car", category: "travel" },
  { emoji: "🚓", name: "police car", category: "travel" },
  { emoji: "🚑", name: "ambulance", category: "travel" },
  { emoji: "🚒", name: "fire engine", category: "travel" },
  { emoji: "✈️", name: "airplane", category: "travel" },
  { emoji: "🚀", name: "rocket", category: "travel" },
  { emoji: "🛸", name: "flying saucer", category: "travel" },
  { emoji: "🚢", name: "ship", category: "travel" },
  { emoji: "⛵", name: "sailboat", category: "travel" },
  { emoji: "🚂", name: "locomotive", category: "travel" },
  { emoji: "🚇", name: "metro", category: "travel" },
  { emoji: "🚆", name: "train", category: "travel" },
  { emoji: "🏠", name: "house", category: "travel" },
  { emoji: "🏡", name: "house with garden", category: "travel" },
  { emoji: "🏢", name: "office building", category: "travel" },
  { emoji: "🏥", name: "hospital", category: "travel" },
  { emoji: "🏦", name: "bank", category: "travel" },
  { emoji: "🏰", name: "castle", category: "travel" },
  { emoji: "🗼", name: "Tokyo tower", category: "travel" },
  { emoji: "🗽", name: "Statue of Liberty", category: "travel" },
  { emoji: "⛰️", name: "mountain", category: "travel" },
  { emoji: "🌋", name: "volcano", category: "travel" },
  { emoji: "🏔️", name: "snow-capped mountain", category: "travel" },
  { emoji: "🏕️", name: "camping", category: "travel" },
  { emoji: "🏖️", name: "beach with umbrella", category: "travel" },
  { emoji: "🌅", name: "sunset", category: "travel" },
  { emoji: "🌄", name: "sunrise over mountains", category: "travel" },
  { emoji: "🌠", name: "shooting star", category: "travel" },
  { emoji: "🎆", name: "fireworks", category: "travel" },
  { emoji: "🎇", name: "sparkler", category: "travel" },
  { emoji: "🌍", name: "globe showing Europe-Africa", category: "travel" },
  { emoji: "🌎", name: "globe showing Americas", category: "travel" },
  { emoji: "🌏", name: "globe showing Asia-Australia", category: "travel" },
  { emoji: "🗺️", name: "world map", category: "travel" },
  { emoji: "🧭", name: "compass", category: "travel" },
  { emoji: "⌚", name: "watch", category: "objects" },
  { emoji: "📱", name: "mobile phone", category: "objects" },
  { emoji: "💻", name: "laptop", category: "objects" },
  { emoji: "⌨️", name: "keyboard", category: "objects" },
  { emoji: "🖥️", name: "desktop computer", category: "objects" },
  { emoji: "🖨️", name: "printer", category: "objects" },
  { emoji: "🖱️", name: "computer mouse", category: "objects" },
  { emoji: "📷", name: "camera", category: "objects" },
  { emoji: "🎥", name: "movie camera", category: "objects" },
  { emoji: "📺", name: "television", category: "objects" },
  { emoji: "📻", name: "radio", category: "objects" },
  { emoji: "🎙️", name: "studio microphone", category: "objects" },
  { emoji: "🎚️", name: "level slider", category: "objects" },
  { emoji: "🎛️", name: "control knobs", category: "objects" },
  { emoji: "🔔", name: "bell", category: "objects" },
  { emoji: "🔑", name: "key", category: "objects" },
  { emoji: "🗝️", name: "old key", category: "objects" },
  { emoji: "🔨", name: "hammer", category: "objects" },
  { emoji: "🪓", name: "axe", category: "objects" },
  { emoji: "🔧", name: "wrench", category: "objects" },
  { emoji: "🔩", name: "nut and bolt", category: "objects" },
  { emoji: "⚙️", name: "gear", category: "objects" },
  { emoji: "💡", name: "light bulb", category: "objects" },
  { emoji: "🔦", name: "flashlight", category: "objects" },
  { emoji: "📚", name: "books", category: "objects" },
  { emoji: "📖", name: "open book", category: "objects" },
  { emoji: "📝", name: "memo", category: "objects" },
  { emoji: "✏️", name: "pencil", category: "objects" },
  { emoji: "🖊️", name: "pen", category: "objects" },
  { emoji: "🖌️", name: "paintbrush", category: "objects" },
  { emoji: "📎", name: "paperclip", category: "objects" },
  { emoji: "📌", name: "pushpin", category: "objects" },
  { emoji: "✂️", name: "scissors", category: "objects" },
  { emoji: "📦", name: "package", category: "objects" },
  { emoji: "📫", name: "closed mailbox with raised flag", category: "objects" },
  { emoji: "🛒", name: "shopping cart", category: "objects" },
  { emoji: "🎁", name: "wrapped gift", category: "objects" },
  { emoji: "🎈", name: "balloon", category: "objects" },
  { emoji: "🎉", name: "party popper", category: "objects" },
  { emoji: "🎀", name: "ribbon", category: "objects" },
  { emoji: "🏆", name: "trophy", category: "objects" },
  { emoji: "🥇", name: "1st place medal", category: "objects" },
  { emoji: "🏅", name: "sports medal", category: "objects" },
  { emoji: "⚽", name: "soccer ball", category: "objects" },
  { emoji: "🏀", name: "basketball", category: "objects" },
  { emoji: "🏈", name: "american football", category: "objects" },
  { emoji: "⚾", name: "baseball", category: "objects" },
  { emoji: "🎾", name: "tennis", category: "objects" },
  { emoji: "🎱", name: "pool 8 ball", category: "objects" },
  { emoji: "🏓", name: "ping pong", category: "objects" },
  { emoji: "🏸", name: "badminton", category: "objects" },
  { emoji: "🎯", name: "bullseye", category: "objects" },
  { emoji: "🎮", name: "video game", category: "objects" },
  { emoji: "🎰", name: "slot machine", category: "objects" },
  { emoji: "❤️", name: "red heart", category: "symbols" },
  { emoji: "🧡", name: "orange heart", category: "symbols" },
  { emoji: "💛", name: "yellow heart", category: "symbols" },
  { emoji: "💚", name: "green heart", category: "symbols" },
  { emoji: "💙", name: "blue heart", category: "symbols" },
  { emoji: "💜", name: "purple heart", category: "symbols" },
  { emoji: "🖤", name: "black heart", category: "symbols" },
  { emoji: "🤍", name: "white heart", category: "symbols" },
  { emoji: "🤎", name: "brown heart", category: "symbols" },
  { emoji: "💔", name: "broken heart", category: "symbols" },
  { emoji: "💕", name: "two hearts", category: "symbols" },
  { emoji: "💞", name: "revolving hearts", category: "symbols" },
  { emoji: "💓", name: "beating heart", category: "symbols" },
  { emoji: "💗", name: "growing heart", category: "symbols" },
  { emoji: "💖", name: "sparkling heart", category: "symbols" },
  { emoji: "💘", name: "heart with arrow", category: "symbols" },
  { emoji: "💝", name: "heart with ribbon", category: "symbols" },
  { emoji: "✨", name: "sparkles", category: "symbols" },
  { emoji: "⭐", name: "star", category: "symbols" },
  { emoji: "🌟", name: "glowing star", category: "symbols" },
  { emoji: "💫", name: "dizzy", category: "symbols" },
  { emoji: "🔥", name: "fire", category: "symbols" },
  { emoji: "💯", name: "hundred points", category: "symbols" },
  { emoji: "✅", name: "check mark button", category: "symbols" },
  { emoji: "❌", name: "cross mark", category: "symbols" },
  { emoji: "⭕", name: "hollow red circle", category: "symbols" },
  { emoji: "❗", name: "red exclamation mark", category: "symbols" },
  { emoji: "❓", name: "red question mark", category: "symbols" },
  { emoji: "⚠️", name: "warning", category: "symbols" },
  { emoji: "🚫", name: "prohibited", category: "symbols" },
  { emoji: "♻️", name: "recycling symbol", category: "symbols" },
  { emoji: "🔴", name: "red circle", category: "symbols" },
  { emoji: "🟠", name: "orange circle", category: "symbols" },
  { emoji: "🟡", name: "yellow circle", category: "symbols" },
  { emoji: "🟢", name: "green circle", category: "symbols" },
  { emoji: "🔵", name: "blue circle", category: "symbols" },
  { emoji: "🟣", name: "purple circle", category: "symbols" },
  { emoji: "⬛", name: "black large square", category: "symbols" },
  { emoji: "⬜", name: "white large square", category: "symbols" },
  { emoji: "🔶", name: "large orange diamond", category: "symbols" },
  { emoji: "🔷", name: "large blue diamond", category: "symbols" },
  { emoji: "🔺", name: "red triangle pointed up", category: "symbols" },
  { emoji: "🔻", name: "red triangle pointed down", category: "symbols" },
  { emoji: "💠", name: "diamond with a dot", category: "symbols" },
  { emoji: "🔘", name: "radio button", category: "symbols" },
  { emoji: "♈", name: "Aries", category: "symbols" },
  { emoji: "♉", name: "Taurus", category: "symbols" },
  { emoji: "♊", name: "Gemini", category: "symbols" },
  { emoji: "♋", name: "Cancer", category: "symbols" },
  { emoji: "♌", name: "Leo", category: "symbols" },
  { emoji: "♍", name: "Virgo", category: "symbols" },
  { emoji: "♎", name: "Libra", category: "symbols" },
  { emoji: "♏", name: "Scorpio", category: "symbols" },
  { emoji: "♐", name: "Sagittarius", category: "symbols" },
  { emoji: "♑", name: "Capricorn", category: "symbols" },
  { emoji: "♒", name: "Aquarius", category: "symbols" },
  { emoji: "♓", name: "Pisces", category: "symbols" },
]

const CATEGORIES = [
  { key: "smileys", label: "Smileys" },
  { key: "people", label: "People" },
  { key: "animals", label: "Animals" },
  { key: "food", label: "Food" },
  { key: "travel", label: "Travel" },
  { key: "objects", label: "Objects" },
  { key: "symbols", label: "Symbols" },
]

function getUnicode(emoji: string): string {
  const codePoints: string[] = []
  for (let i = 0; i < emoji.length; ) {
    const cp = emoji.codePointAt(i)!
    codePoints.push(`U+${cp.toString(16).toUpperCase().padStart(4, "0")}`)
    i += cp > 0xffff ? 2 : 1
  }
  return codePoints.join(" ")
}

export default function EmojiPicker() {
  const [search, setSearch] = useState("")
  const [category, setCategory] = useState("smileys")
  const [copiedEmoji, setCopiedEmoji] = useState("")

  const filtered = useMemo(() => {
    const q = search.toLowerCase()
    return EMOJI_DATA.filter(
      (e) =>
        e.category === category &&
        (q === "" || e.name.includes(q) || e.emoji.includes(q))
    )
  }, [search, category])

  const copyEmoji = useCallback((emoji: string) => {
    navigator.clipboard.writeText(emoji)
    setCopiedEmoji(emoji)
    setTimeout(() => setCopiedEmoji(""), 1500)
  }, [])

  const inputStyle = {
    backgroundColor: "var(--color-surface)",
    borderColor: "var(--color-border)",
    color: "var(--color-text)",
  }

  return (
    <div className="space-y-4">
      <input
        type="text"
        className="w-full p-2 rounded-lg border text-sm"
        style={inputStyle}
        placeholder="Search emojis..."
        value={search}
        onChange={(e) => setSearch(e.target.value)}
      />

      <div className="flex flex-wrap gap-1">
        {CATEGORIES.map((c) => (
          <button
            key={c.key}
            onClick={() => { setCategory(c.key); setSearch(""); }}
            className={`px-3 py-1 rounded-lg text-xs font-medium transition-colors ${
              category === c.key
                ? "text-white"
                : "text-[var(--color-text-secondary)] border border-[var(--color-border)] hover:bg-[var(--color-surface-hover)]"
            }`}
            style={category === c.key ? { backgroundColor: "var(--color-primary)" } : {}}
          >
            {c.label}
          </button>
        ))}
      </div>

      <div className="grid grid-cols-8 sm:grid-cols-10 md:grid-cols-12 gap-1 max-h-96 overflow-y-auto p-1">
        {filtered.map((e) => (
          <button
            key={e.emoji + e.name}
            title={`${e.name}\n${getUnicode(e.emoji)}${copiedEmoji === e.emoji ? "\nCopied!" : ""}`}
            onClick={() => copyEmoji(e.emoji)}
            className="text-2xl p-1 rounded hover:bg-[var(--color-surface-hover)] transition-colors cursor-pointer flex items-center justify-center aspect-square"
          >
            {e.emoji}
          </button>
        ))}
      </div>

      {copiedEmoji && (
        <p className="text-sm" style={{ color: "var(--color-primary)" }}>
          Copied {copiedEmoji}
        </p>
      )}

      <p className="text-xs" style={{ color: "var(--color-text-secondary)" }}>
        {filtered.length} emojis · Click to copy
      </p>
    </div>
  )
}
